-- ZAIKO AI STUDIO - PostgreSQL schema
-- Run this once in Supabase SQL Editor.
-- Existing users/voices are migrated separately with:
--   python database.py --migrate-json users_db.json

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(255) not null,
    is_active boolean not null default true,
    is_admin boolean not null default false,
    remaining_chars bigint not null default 0,
    total_limit bigint not null default 0,
    total_credits_allocated bigint not null default 0,
    access_expires_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.credentials (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users(id) on delete cascade,
    kaggle_username_enc text not null,
    kaggle_token_enc text not null,
    ngrok_token_enc text not null default '',
    ngrok_domain_enc text not null default '',
    updated_at timestamptz not null default now()
);

create table if not exists public.deployments (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users(id) on delete cascade,
    kernel_id varchar(200) not null unique,
    kernel_slug varchar(120) not null,
    public_url varchar(500),
    status varchar(40) not null default 'IDLE',
    last_error text,
    last_logs text,
    updated_at timestamptz not null default now()
);

create table if not exists public.login_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    token_hash varchar(64) not null unique,
    expires_at timestamptz not null,
    created_at timestamptz not null default now()
);

create table if not exists public.saved_voices (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    name varchar(120) not null,
    filename varchar(255) not null,
    mime_type varchar(120),
    encrypted_audio bytea not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_users_username on public.users(username);
create index if not exists idx_login_sessions_token_hash on public.login_sessions(token_hash);
create index if not exists idx_login_sessions_user_id on public.login_sessions(user_id);
create index if not exists idx_saved_voices_user_id on public.saved_voices(user_id);
create index if not exists idx_credentials_user_id on public.credentials(user_id);
create index if not exists idx_deployments_user_id on public.deployments(user_id);

create or replace function public.zaiko_set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists zaiko_credentials_updated_at on public.credentials;
create trigger zaiko_credentials_updated_at
before update on public.credentials
for each row execute function public.zaiko_set_updated_at();

drop trigger if exists zaiko_deployments_updated_at on public.deployments;
create trigger zaiko_deployments_updated_at
before update on public.deployments
for each row execute function public.zaiko_set_updated_at();

-- The Streamlit server connects with DATABASE_URL, not the browser.
-- Keep these tables inaccessible to anon/authenticated clients unless you
-- intentionally add a browser-side API later.
alter table public.users enable row level security;
alter table public.credentials enable row level security;
alter table public.deployments enable row level security;
alter table public.login_sessions enable row level security;
alter table public.saved_voices enable row level security;

revoke all on table public.users from anon, authenticated;
revoke all on table public.credentials from anon, authenticated;
revoke all on table public.deployments from anon, authenticated;
revoke all on table public.login_sessions from anon, authenticated;
revoke all on table public.saved_voices from anon, authenticated;
